export const CLASE_SUPERFICIE: Record<string, string> = {
  azul: 'bg-azul-categoria',
  verde: 'bg-verde-categoria',
  morado: 'bg-morado-categoria',
  naranja: 'bg-naranja-categoria',
  rosa: 'bg-rosa-categoria',
  rojo: 'bg-rojo-categoria',
  gris: 'bg-gris-categoria',
  amarillo: 'bg-amarillo-categoria',
  cian: 'bg-cian-categoria',
  cyan: 'bg-cian-categoria',
  teal: 'bg-teal-categoria',
  violeta: 'bg-violeta-categoria',
  'azul-claro': 'bg-azul-claro-categoria',
  musica: 'bg-verde-categoria',
  tecnologia: 'bg-violeta-categoria',
  negocios: 'bg-amarillo-categoria',
  empresa: 'bg-naranja-categoria',
  educacion: 'bg-azul-categoria',
  reuniones: 'bg-rosa-categoria',
  otros: 'bg-gris-categoria',
  gastronomia: 'bg-naranja-categoria',
}

export const CLASE_TEXTO: Record<string, string> = {
  azul: 'text-azul-categoria',
  verde: 'text-verde-categoria',
  morado: 'text-morado-categoria',
  naranja: 'text-naranja-categoria',
  rosa: 'text-rosa-categoria',
  rojo: 'text-rojo-categoria',
  gris: 'text-gris-categoria',
  amarillo: 'text-amarillo-categoria',
  cian: 'text-cian-categoria',
  cyan: 'text-cian-categoria',
  teal: 'text-teal-categoria',
  violeta: 'text-violeta-categoria',
  'azul-claro': 'text-azul-claro-categoria',
  tecnologia: 'text-violeta-categoria',
  negocios: 'text-rosa-categoria',
  educacion: 'text-azul-categoria',
  gastronomia: 'text-naranja-categoria',
}

export const CLASE_DEGRADADO: Record<string, string> = {
  morado: 'degradado-morado',
  azul: 'degradado-azul',
  calido: 'degradado-calido',
  verde: 'degradado-verde',
  rosa: 'degradado-rosa',
  nocturno: 'degradado-nocturno',
  'rosa-suave': 'degradado-rosa-suave',
  'violeta-suave': 'degradado-violeta-suave',
  teal: 'degradado-teal',
  tecnologia: 'degradado-violeta-suave',
  negocios: 'degradado-rosa-suave',
  educacion: 'degradado-educativo',
  gastronomia: 'degradado-gastronomico',
  primario: 'degradado-primario',
}
