export const NOMBRES_ICONOS = [
  'actividad', 'adjuntar', 'ajustes-sistema', 'alerta-roja', 'amigos-todos', 'amigos',
  'archivo-hoja', 'archivo-pdf', 'bloqueado', 'buscar', 'caja', 'calendario', 'campana',
  'carrito', 'categoria-evento', 'cerrar', 'clave', 'cohete', 'colaborador', 'comentario',
  'compartir', 'compras', 'configuracion', 'contabilidad', 'corona', 'crear-evento',
  'cuadricula', 'despedida', 'editar', 'empresa', 'encuesta', 'enviar', 'estadisticas',
  'estrella', 'fijar', 'flecha-abajo-izquierda', 'flecha-arriba-derecha', 'filtro',
  'filtros', 'flecha-abajo', 'flecha-derecha', 'flecha-izquierda', 'fuego', 'microfono',
  'altavoz', 'enlace', 'actualizar', 'escudo', 'pantalla-compartida', 'microfono-apagado',
  'video-apagado', 'flecha-arriba', 'punto-circular', 'sin-acceso', 'ver', 'eliminar',
  'imprimir', 'descargar', 'alerta', 'correo', 'tarjeta-pago', 'documento', 'guardar',
  'idea', 'grupos', 'guardado', 'imagen', 'indicador', 'informacion', 'inicio-sesion',
  'inicio', 'intercambio', 'inventario', 'listas', 'llamada', 'maletin', 'mantenimiento',
  'mas', 'me-gusta', 'mensaje', 'menu-hamburguesa', 'moneda', 'mundo', 'nuevo-usuario',
  'panel', 'planillas', 'puntos', 'rapido', 'reporte', 'reportes-barra', 'respaldo',
  'respetado', 'sentimiento', 'silenciado', 'sistema', 'solicitudes', 'soporte', 'tienda',
  'ubicacion', 'ventas', 'verificado', 'video', 'reloj',
] as const

export const MAPA_ICONOS = {
  inicio: 'inicio',
  actividad: 'actividad',
  notificaciones: 'campana',
  campana: 'campana',
  mensajes: 'mensaje',
  amigos: 'amigos',
  usuarios: 'amigos',
  grupos: 'grupos',
  marketplace: 'tienda',
  eventos: 'calendario',
  guardados: 'guardado',

  colaboradores: 'colaborador',
  dashboard: 'panel',
  estadisticas: 'estadisticas',
  reportes: 'reporte',
  indicadores: 'indicador',

  'foto-video': 'imagen',
  encuesta: 'encuesta',
  sentimiento: 'sentimiento',
  'me-gusta': 'me-gusta',
  estrella: 'estrella',
  comentario: 'comentario',
  compartir: 'compartir',

  mas: 'mas',
  puntos: 'puntos',
  buscar: 'buscar',
  configuracion: 'configuracion',
  cerrar: 'cerrar',
  video: 'video',
  llamada: 'llamada',
  adjuntar: 'adjuntar',
  enviar: 'enviar',
  filtros: 'filtros',
  listas: 'listas',
  bloqueado: 'bloqueado',
  solicitudes: 'solicitudes',
  'amigos-todos': 'amigos-todos',
  editar: 'editar',
  informacion: 'informacion',
  fijar: 'fijar',
  silenciado: 'silenciado',

  'flecha-abajo': 'flecha-abajo',
  reloj: 'reloj',
  'flecha-derecha': 'flecha-derecha',
  'flecha-izquierda': 'flecha-izquierda',
  'flecha-abajo-izquierda': 'flecha-abajo-izquierda',
  'flecha-arriba-derecha': 'flecha-arriba-derecha',
  microfono: 'microfono',
  altavoz: 'altavoz',
  enlace: 'enlace',
  actualizar: 'actualizar',
  calendario: 'calendario',
  escudo: 'escudo',
  'pantalla-compartida': 'pantalla-compartida',
  'microfono-apagado': 'microfono-apagado',
  'video-apagado': 'video-apagado',
  'flecha-arriba': 'flecha-arriba',
  'punto-circular': 'punto-circular',
  'sin-acceso': 'sin-acceso',
  ver: 'ver',
  eliminar: 'eliminar',
  imprimir: 'imprimir',
  descargar: 'descargar',
  alerta: 'alerta',
  correo: 'correo',
  'tarjeta-pago': 'tarjeta-pago',
  documento: 'documento',
  guardar: 'guardar',
  idea: 'idea',

  'menu-hamburguesa': 'menu-hamburguesa',
  cuadricula: 'cuadricula',
  empresa: 'empresa',
  moneda: 'moneda',
  caja: 'caja',
  maletin: 'maletin',
  grilla: 'cuadricula',

  mundo: 'mundo',
  visibilidad: 'mundo',
  sistema: 'sistema',
  'archivo-pdf': 'archivo-pdf',
  'archivo-hoja': 'archivo-hoja',

  'inicio-sesion': 'inicio-sesion',
  'nuevo-usuario': 'nuevo-usuario',
  clave: 'clave',
  'ajustes-sistema': 'ajustes-sistema',
  respaldo: 'respaldo',
  'alerta-roja': 'alerta-roja',
  mantenimiento: 'mantenimiento',

  intercambio: 'intercambio',
  despedida: 'despedida',

  contabilidad: 'contabilidad',
  compras: 'compras',
  ventas: 'ventas',
  inventario: 'inventario',
  planillas: 'planillas',
  'reportes-barra': 'reportes-barra',

  verificado: 'verificado',
  rapido: 'rapido',
  soporte: 'soporte',
  carrito: 'carrito',
  cohete: 'cohete',
  'mis-compras': 'compras',

  'crear-evento': 'crear-evento',
  ubicacion: 'ubicacion',
  filtro: 'filtro',
  'categoria-evento': 'categoria-evento',
  corona: 'corona',
  fuego: 'fuego',
} as const
