export const NOMBRES_ICONOS = [
  'actividad', 'adjuntar', 'ajustes-sistema', 'aviso-critico', 'amigos-todos', 'amigos',
  'archivo-hoja', 'archivo-pdf', 'bloqueado', 'buscar', 'caja', 'calendario', 'campana',
  'carrito', 'categoria-evento', 'cerrar', 'clave', 'cohete', 'colaborador', 'comentario',
  'compartir', 'compras', 'configuracion', 'contabilidad', 'corona', 'crear-evento',
  'cuadricula', 'despedida', 'editar', 'empresa', 'encuesta', 'enviar', 'estadisticas',
  'estrella', 'fijar', 'flecha-abajo-izquierda', 'flecha-arriba-derecha', 'filtro',
  'filtros', 'flecha-abajo', 'flecha-derecha', 'flecha-izquierda', 'fuego', 'microfono',
  'altavoz', 'enlace', 'actualizar', 'escudo', 'pantalla-compartida', 'microfono-apagado',
  'video-apagado', 'flecha-arriba', 'punto-circular', 'sin-acceso', 'ver', 'eliminar',
  'imprimir', 'descargar', 'aviso', 'correo', 'tarjeta-pago', 'documento', 'guardar',
  'idea', 'grupos', 'guardado', 'imagen', 'indicador', 'informacion', 'inicio-sesion',
  'inicio', 'intercambio', 'inventario', 'listas', 'llamada', 'maletin', 'mantenimiento',
  'mas', 'me-gusta', 'mensaje', 'menu-hamburguesa', 'moneda', 'mundo', 'nuevo-usuario',
  'panel', 'planillas', 'puntos', 'rapido', 'reporte', 'reportes-barra', 'respaldo',
  'respetado', 'sentimiento', 'silenciado', 'sistema', 'solicitudes', 'soporte', 'tienda',
  'ubicacion', 'ventas', 'verificado', 'video', 'reloj',
] as const
